name: Check OOP lab

on:
  pull_request:

jobs:
  check-dirs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Determine changed directories
        id: changes
        run: |
          CHANGED_DIRS=$(git diff --name-only ${{ github.sha }} ${{ github.event.before }} | grep -E '^OOP/lab_[0-9]+/[a-zA-Z.]+/|^OOP/practice_[0-9]+/[a-zA-Z.]+/' | cut -d'/' -f1,2 | sort -u)

          if [ -n "$CHANGED_DIRS" ]; then
            echo "Changed directories: $CHANGED_DIRS"
            echo "::set-output name=dirs::$CHANGED_DIRS"
          else
            echo "No relevant changes found"
            exit 0
          fi

  build:
    runs-on: ubuntu-latest
    needs: check-dirs
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build each lab with Gradle
        run: |
          for DIR in ${{ needs.check-dirs.steps.changes.outputs.dirs }}; do
            echo "Running build in $DIR"
            cd $DIR
            gradle build
            cd ${{ github.workspace }}
          done
